### ISSUE TITLE
0.1.7版本装不上~·

### ISSUE THREAD

**Issue by waffle105** [dice2o/BingGPT#12]
压缩包解压后提示  不存在~

**Comment by dice2o** [comment]
Which platform are you using? I tested the zip file for Windows and did not reproduce same situation.

**Comment by waffle105** [comment]
[BingGPT-0.1.7-win32-x64-Setup.exe]
[BingGPT-0.1.7-win32-x64.zip]
Thank you. I tried the two methods before, but just now I downloaded and extracted it again, and found that it worked. 

Thank you very much for your response!
