### ISSUE TITLE
[SUGGESTION] Add Microsoft Image creator 

### ISSUE THREAD

**Issue by diego12fg** [dice2o/BingGPT#136]
Hello, could be great to also integrate a button for use image creator, this uses DALL-E and it's free.
![image](https://user-images.githubusercontent.com/73119128/232688387-91da4ec2-1069-43a2-b707-7fd22131c25d.png)
I attached a picture here where you can find

**Comment by guobing1993** [comment]
input 'create me an image of xxx' 
<img width="661" alt="image" src="https://user-images.githubusercontent.com/22333388/232720980-a62ea82f-d98b-43e4-8d96-cfda4fc5a964.png">
