### ISSUE TITLE
MacOS 10.13 打开卡在空白

### ISSUE THREAD

**Issue by lopins** [dice2o/BingGPT#142]
![image](https://user-images.githubusercontent.com/44494732/233262988-5394fc41-638f-4a4f-b510-1b2c7e40ccc1.png)

**Comment by JAYlu1108** [comment]
Win10打开也是空白

**Comment by sunroad** [comment]
要开全局代理，才可以。

**Comment by Jamesweiym** [comment]
为什么网页版可以使用，这个必须要开全局，需要多加什么分流规则

**Comment by Lopins** [comment]
> 

应该不是这个原因，我在Win10和MacOS10.13上，均无法打开，都开了全局代理，绕过中国大陆常见和局域网，都安装了nodejs，代理节点俄罗斯
