### ISSUE TITLE
遇到不能登陆的问题

### ISSUE THREAD

**Issue by Zeaphyou** [dice2o/BingGPT#17]
你好，我遇到点击sign to chat就跳转到 https://edgeservices.bing.com/edgesvc/urlredirect?scenario=waitlist 然后这个页面是空白的，但是点击底下的了解详细信息，就显示我已经加入new bing的欢迎页面，已经通过surge对相关规则进行了设置，通过日本的节点对bing进行代理，这里不能发视频，我将相关情况录屏了在telegram： https://t.me/zhetengsha_group/116558/259260 
麻烦能够解答一下原因

**Comment by dice2o** [comment]
The latest version 0.2.1 has solved this issue. You can download it from release page.

**Comment by Zeaphyou** [comment]
> The latest version 0.2.1 has solved this issue. You can download it from release page.

刚下载测试了，确实已经修复了，可以登陆了。感谢
