### ISSUE TITLE
how can I fix this problem？

### ISSUE THREAD

**Issue by waffle105** [dice2o/BingGPT#18]
Why does my BingGPT always show 'not available'？
![微信截图_20230319184243](https://user-images.githubusercontent.com/24437265/226170226-909b5044-25c1-4401-b5c1-b9105980f331.png)

**Comment by waffle105** [comment]
this picture is my system and I choose BingGPT-0.2.1-win32-x64.zip (Portable).
![微信截图_20230319184701](https://user-images.githubusercontent.com/24437265/226170402-23591929-e511-4050-b4ad-c5908d0152d6.png)

**Comment by dice2o** [comment]
VPN is required when launching the app if new Bing is not available in your area. Make sure bing.com and its subdomains are included in proxy rules. You can exit VPN while chatting.

**Comment by waffle105** [comment]
Got it! It still need VPN~

**Comment by waffle105** [comment]
thank you！ it works now！
