### ISSUE TITLE
增加一个一键导出对话记录的问题

### ISSUE THREAD

**Issue by eleven-monkey** [dice2o/BingGPT#20]
new bing 有对话轮数限制，超过限制后就要强制开启新话题，原来的内容就都被清空了。希望能增加一个一键导出对话记录的功能，会方便不少，多谢了。

**Comment by dice2o** [comment]
BingGPT supports exporting full conversation as image from v0.1.7.
PDF and markdown will be supported in the next release.

**Comment by dice2o** [comment]
BingGPT 0.3.0 has been released, which supports markdown, png and pdf export.
