### ISSUE TITLE
Blank window, no actions possible

### ISSUE THREAD

**Issue by alexisphilip** [dice2o/BingGPT#202]
On BingGPT opening, a blank window opens, but no login form or chat appears. Couldn't login once, only the blank window opens.

Blank window:

![image](https://github.com/dice2o/BingGPT/assets/52562620/c901842b-5709-4793-bc55-11cc9a34bd2d)

Downloads I tried which should work on Windows, but don't work:

- BingGPT-0.3.4-win32-x64-Setup.exe (Installer)
- BingGPT-0.3.4-win32-x64.zip (Portable)

Details:

- OS: Windows 10 Pro (Windows Feature Experience Pack 1000.19041.1000.0)
- OS version: 22H2
- OS build: 19045.2965
- Country: France (no VPN)

If you need more info, don't hesitate to ask.

Update:
Seems to happen on MacOS too ([see GH issue](https://github.com/dice2o/BingGPT/issues/203)).

**Comment by ACholec** [comment]
so did i

**Comment by che808** [comment]
I also get this issue

**Comment by rugabunda** [comment]
i get this, which i cannot close

![image](https://github.com/dice2o/BingGPT/assets/38260267/4ad67b48-ae5e-4536-864d-281f4d031736)

**Comment by SouperGeng** [comment]
我也一样

**Comment by liquanlin1** [comment]
I got the same question.

**Comment by XHXiaoHuang** [comment]
I just opened edge and found that it updated itself, and mine was blank as well

**Comment by keviiince** [comment]
Same Problem.

**Comment by HiNoneFly** [comment]
I had the same problem

**Comment by qadws007** [comment]
me too

**Comment by 343830384** [comment]
+1

**Comment by romantech** [comment]
same issue for me

**Comment by Dawn-K** [comment]
Me too.

**Comment by whh1009** [comment]
+1

**Comment by howeie** [comment]
the same

**Comment by XHT12333** [comment]
我也是空白的不可以使用了

**Comment by GamerXCZ** [comment]
Same on me

**Comment by GeminiSHEN** [comment]
我也是一直用了一段时间，然后这连天就突然不能用了，删除重新下载也是这样的，打不开

**Comment by comradeWong** [comment]
I got the same problem, does anyone have a good solution？

**Comment by galanz01** [comment]
Same problem.

**Comment by 5a5ch4** [comment]
<img width="443" alt="image" src="https://github.com/dice2o/BingGPT/assets/38190757/ea4a54de-167a-4f40-b191-a3af0ead0ede">

**Comment by GeminiSHEN** [comment]
大家别搞机场了，我换了梯子，机场，甚至自己搭建了一个机场，都没解决，感觉应该不是机场的问题（因为在edge能打开new 
 bing），降版本也试过了。  结果打开还是纯白色。如果有大哥能解决的话，麻烦请踢我一下，我很着急。

**Comment by zhangzhiming5** [comment]
如果有大哥能解决的话，麻烦请踢我一下，我很着急

**Comment by keviiince** [comment]
> 大家别搞机场了，我换了梯子，机场，甚至自己搭建了一个机场，都没解决，感觉应该不是机场的问题（因为在edge能打开new bing），降版本也试过了。 结果打开还是纯白色。如果有大哥能解决的话，麻烦请踢我一下，我很着急。

着急用可以去网页版找bingchat啊，应该是一样的吧

**Comment by WarriorCV** [comment]
兄弟们更新版本了，上啊！！！！！

**Comment by keviiince** [comment]
楼上的兄弟们，新版本修复了

hey guys on upstairs, the new version has fixed the issue of blank spaces

**Comment by alexisphilip** [comment]
Corrected on my setup (see this issue's description for specs). Closing issue.
