### ISSUE TITLE
problem start binggpt with mac silicon M1

### ISSUE THREAD

**Issue by alexonbstudio** [dice2o/BingGPT#211]
![Uploading Capture d’écran 2023-05-14 à 17.19.33.png…]()

**Comment by alexonbstudio** [comment]
https://ibb.co/RPhQ1dF

**Comment by Rvsultan** [comment]
Same problem with mac silicon M2

**Comment by xiurui-pan** [comment]
same problem here with m1 pro

**Comment by zhucp18** [comment]
Run this code in the terminal
@alexonbstudio @Rvsultan @xiurui-pan 

`xattr -rd com.apple.quarantine /Applications/BingGPT.app`
