### ISSUE TITLE
why only 5 responses ?

### ISSUE THREAD

**Issue by TawhidsShadow** [dice2o/BingGPT#223]

**Comment by cxknmsl0071** [comment]
Because you can only talk five times if you are not logged in, we need a login key

**Comment by Komorebi-yaodong** [comment]
I've logged in but I can only get 5 responses.

**Comment by ikdsl** [comment]
我的也是，只有5次，也登录了，求解

**Comment by Komorebi-yaodong** [comment]
这是来自QQ邮箱的自动回复邮件。



    你好,您的邮件我已经收到了，会尽快阅读和处理~~

Komorebi

**Comment by hiwens** [comment]
same

**Comment by keviiince** [comment]
seems to have recovered

**Comment by TawhidsShadow** [comment]
Problem fixed.
