### ISSUE TITLE
Bing 用户每次会话轮次在创意模式下从5次提升到20次了！！！

### ISSUE THREAD

**Issue by Jiangew** [dice2o/BingGPT#228]
Bing 用户每次会话轮次在创意模式下从5次提升到20次了，网页版得到证实，App-0.3.5 版本会话轮次还是5次，可以修复一下，谢谢

**Comment by yxd-python** [comment]
本来就是20次啊
<img width="584" alt="image" src="https://github.com/dice2o/BingGPT/assets/44567379/7f146d84-f475-41a8-b310-ec1f900df0a4">

**Comment by Jiangew** [comment]
在我提 issue 之前，会话轮次一直限制是5，输入的token长度一直是2000 😂

**Comment by Jiangew** [comment]
上午我切换到 bing web 使用了半天，刚才再次切换回 BingGPT App 0.3.5 版本后，会话轮数变成了20，输出token长度也变成了4000 😓，不清楚之间有什么关联，是后端的服务更新了？还是bing记录的我自己的用户偏好变了？没搞清楚。。

**Comment by Jiangew** [comment]
auto fixed, surprised.
