### ISSUE TITLE
对话五次被强迫停止
Dialogue was forced to stop five times

### ISSUE THREAD

**Issue by cxknmsl0071** [dice2o/BingGPT#231]
我的对话在进行到第五次的时候会被强制停止，无论说什么都会让我重新开始，就算它显示我一共可以进行20次对话
My dialogue will be forced to stop at the 5th time, no matter what I say, it will make me start again, even if it shows that I can have a total of 20 dialogues

**Comment by Dawn-K** [comment]
我找到方法了。就是右键有个 reset，点击后会要求重新登陆，登陆之后就可以使用20条了。
I have found a way. That is, there is a reset on the right button. After clicking it, you will be asked to log in again. After logging in, you can use 20 items.

**Comment by dongfengNrq** [comment]
> 我找到方法了。就是右键有个 reset，点击后会要求重新登陆，登陆之后就可以使用20条了。 I have found a way. That is, there is a reset on the right button. After clicking it, you will be asked to log in again. After logging in, you can use 20 items.

方法很管用，感谢。
It works, thanks a lot.
