### ISSUE TITLE
Windows BingGPT 0.3.6 blank page 显示空白

### ISSUE THREAD

**Issue by cxknmsl0071** [dice2o/BingGPT#233]
就算开全局代理也是一直空白
Even if the global agent is enabled, it is always blank.

**Comment by heqinghua217** [comment]
我也是，不知道为啥，咋解决呢

**Comment by keviiince** [comment]
我就知道我不是一个人

**Comment by heqinghua217** [comment]
&nbsp;


老何
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月29日(星期一) 晚上10:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dice2o/BingGPT] Windows BingGPT 0.3.6 blank page 显示空白 (Issue #233)





 
我就知道我不是一个人

**Comment by pemolo** [comment]
> 就算开全局代理也是一直空白 即使启用了全局代理，它也始终为空。即使启用了全局代理，它也始终为空。

原来不止我一个人是这样

**Comment by 1795024193** [comment]
我也这样。

**Comment by otkdl** [comment]
> 就算开全局代理也是一直空白 Even if the global agent is enabled, it is always blank.

右键reset下，重新登录

**Comment by whh1009** [comment]
reset 都按烂了，还是空白。。。

**Comment by keviiince** [comment]
我也又空白了，无语啊

**Comment by szcnshow** [comment]
我也是啊

**Comment by cxknmsl0071** [comment]
我的能用了

**Comment by heqinghua217** [comment]
右键reset下，重新登录，也不行


&nbsp;


老何
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月5日(星期一) 中午12:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dice2o/BingGPT] Windows BingGPT 0.3.6 blank page 显示空白 (Issue #233)





  
就算开全局代理也是一直空白 Even if the global agent is enabled, it is always blank.
  
右键reset下，重新登录
