### ISSUE TITLE
BingGPT-0.3.6-darwin-x64.dmg，安装后一直空白，无反应

### ISSUE THREAD

**Issue by say1921** [dice2o/BingGPT#236]
<img width="602" alt="image" src="https://github.com/dice2o/BingGPT/assets/17819864/ae0f8b51-6de0-4979-8ff1-73097f0bea87">
安装后一直空白，无反应

**Comment by callmewenhao** [comment]
**global proxy** is all you need, look this issue!🤗 https://github.com/dice2o/BingGPT/issues/93
