### ISSUE TITLE
软件包 binggpt-0.3.0-1.x86_64 是针对 different 操作系统的

### ISSUE THREAD

**Issue by XAVIER2020-CLOUD** [dice2o/BingGPT#24]
fedora37显示：软件包 binggpt-0.3.0-1.x86_64 是针对 different 操作系统的

**Comment by dice2o** [comment]
I have recompiled and uploaded the packages for Linux, you can download it again from release page.

**Comment by XAVIER2020-CLOUD** [comment]
> 

amazing，太好用了
