### ISSUE TITLE
Continue bro.

### ISSUE THREAD

**Issue by foxypiratecove37350** [dice2o/BingGPT#320]
Continue this app bro, we are with you! You want one thing? We will help you! Just ask we!

**Comment by TechElliott** [comment]
MS broke the app. Just use copilot.Microsoft.com to get the same thing. It works on chrome and Edge

**Comment by foxypiratecove37350** [comment]
> MS broke the app. Just use copilot.Microsoft.com to get the same thing. It works on chrome and Edge

I know, it was just to motivate this great man who made this app, to continue to maintain this app. But if he don't want, it's his choice.

**Comment by foxypiratecove37350** [comment]
I... fixed the app and adapted it to Microsoft Copilot V2...
