### ISSUE TITLE
中文问题，回复只有英文

### ISSUE THREAD

**Issue by popappu** [dice2o/BingGPT#33]
之前bing没有被屏蔽之前，用中文提问，虽然bigchat会先翻译为英文然后搜索资料，再输出中文答案，但是这个目前只回复英文，如何解决

**Comment by QwindF** [comment]
第一句话先说“你好”或者“请用中文回答我的问题，并且在接下来的对话中一直保持”

**Comment by dice2o** [comment]
The language of Bing's replies depends on the language of your first message.

**Comment by popappu** [comment]
> 第一句话先说“你好”或者“请用中文回答我的问题，并且在接下来的对话中一直保持”

好的，谢谢 我试试
