### ISSUE TITLE
Feature request: support displaying images

### ISSUE THREAD

**Issue by RayGicEFL** [dice2o/BingGPT#36]
Bing AI now supports creating pictures for the user, but it seems that BingGPT's chat box cannot show that.
<img width="1120" alt="browser" src="https://user-images.githubusercontent.com/96906415/227845828-ed2dc103-5d6a-430e-9e07-10f37526b5cb.png">
<img width="1120" alt="binggpt" src="https://user-images.githubusercontent.com/96906415/227845852-fddf657d-6db8-49ac-8979-5c89146b1867.png">

**Comment by dice2o** [comment]
I did a test and it works fine.
<img width="690" alt="test" src="https://user-images.githubusercontent.com/3584724/227910522-abc3f5f7-a752-4264-aa43-1be4971d3c1f.png">

**Comment by RayGicEFL** [comment]
I also tested several tines before. It might appear only on Windows, I'm not sure. Let me take some investigation. Hoever, thanks for the nice software~

**Comment by RayGicEFL** [comment]
It's fine now.
![Pic](https://user-images.githubusercontent.com/96906415/228136202-943f7974-14a4-42b7-bac1-a7b0cb6ffcf6.png)
