### ISSUE TITLE
Feature Request: macOS app icon that conforms to Apple's standard

### ISSUE THREAD

**Issue by Jerry23011** [dice2o/BingGPT#38]
Hi, I think an app icon that meets [Apple's human interface standards](https://developer.apple.com/design/human-interface-guidelines/foundations/app-icons/) would be nice on Mac
This [icon](https://parsefiles.back4app.com/JPaQcFfEEQ1ePBxbf6wvzkPMEqKYHhPYv8boI1Rc/51fcbae62cd553123e7eade10753e1f3_GIEifuXoCd.icns) from macosicons.com may serve as a good referenece :)

**Comment by dice2o** [comment]
Thank you for your advice, but this will be the same as the icon of the official Bing app. It's better to make a distinction.

**Comment by Jerry23011** [comment]
It's just the rounded corners, I think the official one is also in rounded corner on the App Store?
<img width="90" alt="截屏2023-03-27 21 01 13" src="https://user-images.githubusercontent.com/89069957/227946438-3e586a4d-ff16-46ac-a695-1a7d5abadeca.png">

**Comment by dice2o** [comment]
Yes. That's why I used the round icon so that users don't confuse it with the official app.

**Comment by Jerry23011** [comment]
So that's why, lol, thanks for explaining.

**Comment by dice2o** [comment]
This is an open source project, if you want to change the icon or something, download the source code, replace `icon.icns`, and make the package for macOS.

**Comment by Jerry23011** [comment]
@Keldos-Li 大佬又来找你了，如果方便的话可以帮忙看看这个吗？🙏🏻
不知道下面的这种怎么样
![Bing_sample](https://user-images.githubusercontent.com/89069957/228093608-7f2ea6c8-b1eb-489b-89b1-b4056b9d7dee.png)

**Comment by Keldos-Li** [comment]
额，这个没必要问我啊，你们觉得可以就可以呀😂。

美观性的事儿我也不想有意见，虽然现在这样可能确实有一点小问题，但我没有兴趣讨论过多的设计细节。

不过，就对照苹果图标的规范性来看，这个图标还需要增加图标阴影。example：
<img width="227" alt="image" src="https://user-images.githubusercontent.com/23137268/228102135-0ad6a3cf-26fc-43f6-9372-8aaf58bd7b73.png">

-----

Well, there's no need to ask me, if you both think it's okay😂. 

I don't want to have a problem with aesthetics of an icon, although there may be a little problem with it now. But I'm not interested in discussing too many design details now. 

However, just compared with the standardization of the Apple Mac icon, the icon needs to be shaded. Example: (image above)

**Comment by Jerry23011** [comment]
I'll just leave the png here in case anyone has the time. I'm not familiar with handling Electron
![BingGPT_Logo sample](https://user-images.githubusercontent.com/89069957/228106311-8897fb62-3148-4be0-9e9e-4ec0705780cd.png)

**Comment by Jerry23011** [comment]
Thanks to @Kamalmalikk 🙏🏻, this is implemented.

**Comment by Jerry23011** [comment]
Thanks to @Kamalmalikk 🙏🏻 This feature is implemented.
