### ISSUE TITLE
Add a keyboard shortcut for clicking the "New Topic" button

### ISSUE THREAD

**Issue by dohsimpson** [dice2o/BingGPT#42]
Right now, we have to move the mouse cursor with mouse to start a new conversation. Having a keyboard shortcut would eliminate the need to use the mouse to do that and therefore achieve a keyboard oriented workflow.

**Comment by dice2o** [comment]
Thanks for your advice, this feature will be added in the next release.

**Comment by dohsimpson** [comment]
works great, thanks for the hard work!
