### ISSUE TITLE
无法使用，登陆后点击【立即聊天】就会跳到系统浏览器搜索Bing AI（已解决）

### ISSUE THREAD

**Issue by liangxiwei** [dice2o/BingGPT#48]
<img width="620" alt="image" src="https://user-images.githubusercontent.com/3124641/228191587-e853e141-c833-4f91-b821-686596bef421.png">

**Comment by QwindF** [comment]
切换你vpn的节点，部分节点会出现这种情况（记得开全局试试)

**Comment by fayewong5406** [comment]
我也是这样，无限循环在这个“立即聊天”页面

**Comment by qccr** [comment]
我的登录之后，重启软件就解决了
