### ISSUE TITLE
how to run this app?

### ISSUE THREAD

**Issue by y0an1** [dice2o/BingGPT#6]
i run 'sudo apt install ./BingGPT-0.1.6-linux-x64.deb' , then ok
but i no see app icon  or app in launcher

**Comment by dice2o** [comment]
If there is no icon displayed, you can execute `/usr/lib/binggpt/BingGPT`.

**Comment by fsoft72** [comment]
please note that on Linux the symlink `/usr/bin/bingpt` is broken.
Please update it to point to `../lib/binggpt/BingGPT`

**Comment by dice2o** [comment]
Symlink issue has been fixed in latest release (0.1.8).
