### ISSUE TITLE
m1芯片mac系统打不开程序

### ISSUE THREAD

**Issue by hy546880109** [dice2o/BingGPT#66]
<img width="680" alt="image" src="https://user-images.githubusercontent.com/44777854/229258354-bf94a064-2864-4e48-b1cf-aff5b5b6386c.png">

**Comment by StormYudi** [comment]
sudo xattr -r -d com.apple.quarantine /Applications/BingGPT.app

**Comment by hy546880109** [comment]
谢谢，已经解决我的问题
