### ISSUE TITLE
window7 运行提示无法定位程序输入点动态链接库，是不支持 win7 系统吗

### ISSUE THREAD

**Issue by dev-lyw** [dice2o/BingGPT#68]
![35f191d49e3b69645a1b267d926b519](https://user-images.githubusercontent.com/110804800/229445708-379b344e-123b-4c18-987d-ff88287ab5e0.png)

**Comment by dice2o** [comment]
Electron and Chromium have ended support of Win7/8/8.1.

**Comment by dev-lyw** [comment]
ok,thanks you
