### ISSUE TITLE
点击 <开始聊天> 按钮，页面没有任何响应

### ISSUE THREAD

**Issue by IlluminateDarkheat** [dice2o/BingGPT#80]
之前可以正常使用，今天打开后显示初始界面
![image](https://user-images.githubusercontent.com/28666767/230708982-b5bb0129-9c9f-4c75-80a3-370204e1f878.png)
，猜测是登录凭证过期需要重新登录。但是点击 <开始聊天> 按钮后，没有跳转登录页面，也没有其他响应。

**Comment by YANG-Hanbin** [comment]
我也有同样的问题，目前也没有解决，但是我猜测，也许可以换几个路线试试

**Comment by walden-jay** [comment]
同样的问题

**Comment by RmTians** [comment]
同样的问题，换线路也无法解决。

**Comment by hurukawatinami** [comment]
感觉是应用的问题，跟线路无关

**Comment by XXTX-TOP** [comment]
同样的问题  :joy:

**Comment by zpc-dragon** [comment]
原来不止我一个

**Comment by Sirlanri** [comment]
+1

**Comment by galanz01** [comment]
俺也一样……但是我的另外一台电脑还可以用，win11的。不知道是什么原因。

**Comment by INEVITABLE888** [comment]
同样的问题

**Comment by feiji190** [comment]
+1

**Comment by i-sunshine** [comment]
+

**Comment by liamhui** [comment]
我的也是啊，同样的问题。上午用的好好的，下午就用不了。

**Comment by 909254** [comment]
同样问题

**Comment by a-M1NG** [comment]
same problem. could you plz solve it🙏

**Comment by camelweiming** [comment]
+1，上午还好好的

**Comment by Nothingness-Void** [comment]
+1我也这样了

**Comment by dice2o** [comment]
Fixed in v0.3.3
Bing made some changes and the page in BingGPT is not able to get the necessary cookie after login.
I'm not sure if this is a bug or if Bing is intentionally restricting access to this page outside of Edge.

**Comment by ViiiPwr** [comment]
It works now. Much appreciated.

**Comment by yangfengwei** [comment]
同，突然就不行了

**Comment by Nothingness-Void** [comment]
> 
更新最新版就行了
