### ISSUE TITLE
MacBook M1 报错：“BingGPT”已损坏，无法打开。 你应该将它移到废纸篓。

### ISSUE THREAD

**Issue by atfa** [dice2o/BingGPT#83]
![截屏2023-04-09 上午10 32 18](https://user-images.githubusercontent.com/16986056/230751135-91d3f341-ef35-4566-a797-b74783b5874e.png)

**Comment by yuquansi** [comment]
me too

**Comment by dice2o** [comment]
Ref: #5

**Comment by yuquansi** [comment]
> Ref: #5

great!

**Comment by zhiliangpersonal** [comment]
对的

**Comment by zhiliangpersonal** [comment]
对的

**Comment by p82919** [comment]
Try `sudo xattr -d com.apple.quarantine /Applications/BingGPT.app` in Terminal.
It works.

**Comment by aminwangaa** [comment]
sudo: xattr-d: command not found

**Comment by aminwangaa** [comment]
> 



> Try `sudo xattr -d com.apple.quarantine /Applications/BingGPT.app` in Terminal. It works.

sudo: xattr-d: command not found .  how to resolve this problem

**Comment by usb2cam** [comment]
great！

**Comment by atfa** [comment]
`sudo xattr -d com.apple.quarantine /Applications/BingGPT.app`
It works.

**Comment by evilinmyheart** [comment]
But why is it all white when i open it
