### ISSUE TITLE
macOs BingGPT-0.3.3 显示空白

### ISSUE THREAD

**Issue by zzuli4519** [dice2o/BingGPT#93]
<img width="606" alt="image" src="https://user-images.githubusercontent.com/8543026/230817489-03981619-12f0-43e3-8924-b9d8508bb1a2.png">

**Comment by CodeMan-cx** [comment]
同样的问题，是怎么回事？

**Comment by CodeMan-cx** [comment]
科学上网需要打开全局模式才行，代理模式显示空白

**Comment by zzuli4519** [comment]
开启全局代理vpn可以解决问题
