### ISSUE TITLE
无限重定向

### ISSUE THREAD

**Issue by liangxiwei** [dice2o/BingGPT#99]
似乎是检测到帐号或者本地环境是中文，然后会添加一个参数mkt=zh-CN重定向。。不知道为啥

(node:69916) electron: Failed to load URL: https://cn.bing.com/edgediscover/query?&lightschemeovr=1&FORM=SHORUN&udscs=1&udsnav=1&setlang=en-US&features=udssydinternal&clientscopes=windowheader,coauthor,chat,&udsframed=1&mkt=zh-CN&mkt=zh-CN&mkt=zh-CN&mkt=zh-CN&mkt=zh-CN&mkt=zh-CN&mkt=zh-CN&mkt=zh-CN&mkt=zh-CN with error: ERR_TOO_MANY_REDIRECTS

**Comment by dice2o** [comment]
VPN is required. Make sure `bing.com` and its subdomains are proxied.
